export { default as Switch } from './components/Switch'
export { default as Link } from './components/Link'
export { default as Redirect } from './components/Redirect'
export { default as Route } from './components/Route'
export * from './components/Route'
export * from './hooks'
export * as history from './history'
